spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liqiming?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    mongodb:
      database: liqiming
      host: localhost
      port: 27017
      username: root
      password: "123456"
  batch:
    jdbc:
      initialize-schema: always

